[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000

[profile.ci]
optimizer = true
optimizer_runs = 1000000
fuzz_runs = 10000

[profile.test]
optimizer = true
optimizer_runs = 1000
verbosity = 2

[profile.deploy]
optimizer = true
optimizer_runs = 1000000
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
